### ISSUE TITLE
Quiz 1A

### ISSUE THREAD

**Issue by danielfirdaus** [STIA1123-A201/QUIZ-1A#4]
1. When a class constructor gets called?
It is called when an instance of the class is created. 
2. If you create 5 objects of a class, then how many time constructors will be called?
its will be called once.
3.  Constructor does not have return type and its name is same as the name class.
the constructor does not have any return type.
4. The purpose of constructor is to initialize an object of a class
To initialize the object of a class while the purpose of a method is to perform a task

**Comment by mfirdaus07** [comment]
https://github.com/mfirdaus07/Quiz/issues/1
