### ISSUE TITLE
Q1 Question 2

### ISSUE THREAD

**Issue by danielfirdaus** [STIA1123-A201/QUIZ-1A#5]
class Car {
String brand;

public Car(){
this.brand = "Proton";

public String getBrand() {
return brand;
}

void run()
{
System.out.println("Car is running...");
}

public static void main(String[] args)
{
Car proton = new Car();
String brand = Proton.getBrand();
System.out.println(brand)
}
}

**Comment by suhadaibrahim** [comment]
[https://github.com/suhadaibrahim/quiz2/issues/1](url)
